name: disertation
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  badges: ^3.1.2
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.8.0
  freezed: ^2.5.2



flutter:
  uses-material-design: true

  assets:
    - assets/car.png
    - assets/cars.png
    - assets/ad_banner1.jpg
    - assets/ad_banner2.jpg
    - assets/customer.png
    - assets/provider.png
    - assets/customerLogin.png
    - assets/serviceProviderLogin.png
    - assets/booking.png
    - assets/service.png
    - assets/finance.png
    - assets/profile.png
    - assets/serviceNew.png
    - assets/detail.png


