// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwdqGV2I4WuPGVEfsTpEsskJMsXdSv6WM',
    appId: '1:410698316306:web:38c098db02970e3cf976cb',
    messagingSenderId: '410698316306',
    projectId: 'vehicle-maintenance-7f86b',
    authDomain: 'vehicle-maintenance-7f86b.firebaseapp.com',
    databaseURL:
        'https://vehicle-maintenance-7f86b-default-rtdb.firebaseio.com',
    storageBucket: 'vehicle-maintenance-7f86b.appspot.com',
    measurementId: 'G-GB1ZLELXSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOutxPWXvUUQYBLvVSonIJ-HGhT7C_T3I',
    appId: '1:410698316306:android:2b3f889951aae37af976cb',
    messagingSenderId: '410698316306',
    projectId: 'vehicle-maintenance-7f86b',
    databaseURL:
        'https://vehicle-maintenance-7f86b-default-rtdb.firebaseio.com',
    storageBucket: 'vehicle-maintenance-7f86b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA07cmOgxU5p75iMdm_lDPI9S9_LBVTzog',
    appId: '1:410698316306:ios:aae0a336536a2a2bf976cb',
    messagingSenderId: '410698316306',
    projectId: 'vehicle-maintenance-7f86b',
    databaseURL:
        'https://vehicle-maintenance-7f86b-default-rtdb.firebaseio.com',
    storageBucket: 'vehicle-maintenance-7f86b.appspot.com',
    iosBundleId: 'com.example.disertation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA07cmOgxU5p75iMdm_lDPI9S9_LBVTzog',
    appId: '1:410698316306:ios:aae0a336536a2a2bf976cb',
    messagingSenderId: '410698316306',
    projectId: 'vehicle-maintenance-7f86b',
    databaseURL:
        'https://vehicle-maintenance-7f86b-default-rtdb.firebaseio.com',
    storageBucket: 'vehicle-maintenance-7f86b.appspot.com',
    iosBundleId: 'com.example.disertation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwdqGV2I4WuPGVEfsTpEsskJMsXdSv6WM',
    appId: '1:410698316306:web:dee5dca8473a6103f976cb',
    messagingSenderId: '410698316306',
    projectId: 'vehicle-maintenance-7f86b',
    authDomain: 'vehicle-maintenance-7f86b.firebaseapp.com',
    databaseURL:
        'https://vehicle-maintenance-7f86b-default-rtdb.firebaseio.com',
    storageBucket: 'vehicle-maintenance-7f86b.appspot.com',
    measurementId: 'G-1BQPJY5YPS',
  );
}
